// Product data synced with ProductCatalog.md
// This replaces the previous sample data with verified affiliate products

import { Product } from '@/components/ProductCard';

export const sampleProducts: Product[] = [
    // Fire Pits, Heaters & Grills
    {
        id: 'solo-stove-yukon-2',
        name: 'Solo Stove Yukon 2.0',
        brand: 'Solo Stove',
        category: 'Fire Pits, Heaters & Grills',
        affiliateLink: 'https://amzn.to/49ImWN8',
        priceTier: '$$$',
        badge: 'Top Pick',
        ctaText: 'Upgrade Your Family Gatherings',
        lifestyleImage: '/images/products/solo-stove-yukon-2.png',
        description: 'Stop playing musical chairs to dodge smoke. This massive 27" 360° airflow fire pit burns off smoke before it reaches you, meaning you can host 10+ people without the campfire smell.',
        features: ['27" Diameter', 'Smokeless Technology', 'Removable Ash Pan', 'Lifetime Warranty'],
    },
    {
        id: 'solo-stove-bonfire-2',
        name: 'Solo Stove Bonfire 2.0',
        brand: 'Solo Stove',
        category: 'Fire Pits, Heaters & Grills',
        affiliateLink: 'https://amzn.to/4b92HL4',
        priceTier: '$$',
        badge: 'Best Seller',
        lifestyleImage: '/images/products/solo-stove-bonfire-2.png',
        description: 'The Goldilocks of fire pits—perfectly sized for patios but portable enough for camping. Delivers a mesmerizing, smoke-free flame that ignites quickly and burns efficiently.',
        features: ['19.5" Diameter', 'Portable with Carry Case', 'Smokeless Burn', 'Stainless Steel'],
    },
    {
        id: 'solo-stove-mesa-xl',
        name: 'Solo Stove Mesa XL',
        brand: 'Solo Stove',
        category: 'Fire Pits, Heaters & Grills',
        affiliateLink: 'https://amzn.to/3YM9O4D',
        priceTier: '$$',
        badge: 'Tabletop Pick',
        ctaText: 'Spark Intimacy Tonight',
        lifestyleImage: '/images/products/solo-stove-mesa-xl.png',
        description: 'Bring the warmth of a fire to your dining table or balcony. This 7-inch tabletop fire pit creates a cozy focal point for date nights, burning pellets or wood with zero hassle.',
        features: ['Tabletop Size', 'Dual Fuel (Pellet/Wood)', 'Includes Stand', 'Mulberry Color'],
    },
    {
        id: 'breeo-x-series-24',
        name: 'Breeo X Series 24',
        brand: 'Breeo',
        category: 'Fire Pits, Heaters & Grills',
        affiliateLink: 'https://amzn.to/4pPmcfd',
        priceTier: '$$$',
        badge: 'Cooking Pro',
        ctaText: 'Master Live-Fire Cooking',
        lifestyleImage: '/images/products/breeo_x24.png',
        description: 'Built like a tank in the USA. This heavy-duty Corten steel fire pit isn\'t just smokeless—it\'s a wood-fired cooking station. Sear steaks on the rim while enjoying a roaring fire.',
        features: ['Corten Steel', 'Smokeless', 'Made in USA', 'Cooking Rim'],
    },
    {
        id: 'breeo-y-series',
        name: 'Breeo Y Series',
        brand: 'Breeo',
        category: 'Fire Pits, Heaters & Grills',
        affiliateLink: 'https://amzn.to/3LVByAT',
        priceTier: '$$',
        badge: 'Most Portable',
        ctaText: 'Pack The Heat',
        lifestyleImage: '/images/products/breeo_y_series.png',
        description: 'The first truly portable smokeless fire pit that doesn\'t compromise on heat. Adjustable legs make it stable on any terrain, from beach sand to tailgate asphalt.',
        features: ['Lightweight', 'Collapsible Legs', 'Carry Handle', 'Smokeless'],
    },
    {
        id: 'outvue-47-fire-pit',
        name: 'OutVue 47" Fire Pit',
        brand: 'OutVue',
        category: 'Fire Pits, Heaters & Grills',
        affiliateLink: 'https://amzn.to/3NqXBjq',
        priceTier: '$$',
        badge: 'Best Value',
        ctaText: 'Upgrade Your BBQ Game',
        lifestyleImage: '/images/products/outvue_firepit.png',
        description: 'Versatile 3-in-1 wood burning fire pit with dual grills. Functions as a BBQ, firepit, and round table all in one unit.',
        features: ['47" Diameter', 'Dual BBQ Grills', 'Table Function', 'Large Capacity'],
    },
    {
        id: 'serenelife-propane-fire-pit',
        name: 'SereneLife Propane Fire Pit Table',
        brand: 'SereneLife',
        category: 'Fire Pits, Heaters & Grills',
        affiliateLink: 'https://amzn.to/4b6nO0t',
        priceTier: '$$$$',
        badge: 'Gas Favorite',
        ctaText: 'Elevate Your Evening',
        lifestyleImage: '/images/products/serenelife_firepit.png',
        description: 'Skip the wood chopping. This 50,000 BTU gas fire table hides the propane tank completely, giving you a clean, modern aesthetic with instant-on warmth.',
        features: ['50,000 BTU', 'Glass Wind Guard', 'Tile Tabletop', 'Hideaway Tank'],
    },
    {
        id: 'generic-round-propane-table',
        name: 'Round Propane Fire Table',
        brand: 'Generic',
        category: 'Fire Pits, Heaters & Grills',
        affiliateLink: 'https://www.amazon.com/dp/B09PRMNR2V',
        priceTier: '$$$',
        badge: 'Modern Look',
        ctaText: 'Go Modern Minimalist',
        lifestyleImage: '/images/products/propane_fire_table.png',
        description: '32.5-inch Flint & Concrete Look, 50,000 BTU. A modern, minimalist round design for contemporary patios.',
        features: ['Concrete Look', '50,000 BTU', 'Push Button Ignition', 'Includes Cover'],
    },
    {
        id: 'ubeesize-grill-mat',
        name: 'UBeesize Grill Mat',
        brand: 'UBeesize',
        category: 'Fire Pits, Heaters & Grills',
        affiliateLink: 'https://amzn.to/3ZnLCpg',
        priceTier: '$',
        badge: 'Safety First',
        ctaText: 'Protect Your Deck',
        lifestyleImage: '/images/products/grill_mat.png',
        description: 'Heat resistant up to 2000°F. Waterproof and oil-proof. Essential for protecting composite or wood decks from fire pit heat.',
        features: ['2000°F Resistance', 'Waterproof', 'Double Sided', 'Easy Clean'],
    },

    // Outdoor Kitchens & Pizza Ovens
    {
        id: 'mont-alpi-island-grill',
        name: 'Mont Alpi MAi805 Island Grill',
        brand: 'Mont Alpi',
        category: 'Outdoor Kitchens & Pizza Ovens',
        affiliateLink: 'https://amzn.to/4pLaX7l',
        priceTier: '$$$$$',
        badge: 'Ultimate Kitchen',
        ctaText: 'Build Your Dream Kitchen',
        lifestyleImage: '/images/products/mont_alpi_grill.png',
        description: 'Why cook inside? A granite-topped beast with 6 burners, infrared rear burner, and LED lights. It\'s not just a grill; it\'s a complete island that anchors your patio.',
        features: ['6 Burners', 'Infrared Rear Burner', 'Granite Top', 'LED Lights'],
    },
    {
        id: 'ooni-karu-2-pro',
        name: 'Ooni Karu 2 Pro',
        brand: 'Ooni',
        category: 'Outdoor Kitchens & Pizza Ovens',
        affiliateLink: 'https://amzn.to/4jTP2K2',
        priceTier: '$$$$',
        badge: 'Pizza Pro',
        ctaText: 'Become The Pizza Pro',
        lifestyleImage: '/images/products/ooni-karu-2-pro.png',
        description: 'Multi-Fuel Pizza Oven (Wood/Gas/Charcoal). Hits 950°F and cooks restaurant-quality 16-inch pizzas in just 60 seconds.',
        features: ['Multi-Fuel', '16" Capacity', 'Glass Door', 'Digital Thermometer'],
    },
    {
        id: 'gozney-roccbox',
        name: 'Gozney Roccbox',
        brand: 'Gozney',
        category: 'Outdoor Kitchens & Pizza Ovens',
        affiliateLink: 'https://amzn.to/49xXXgO',
        priceTier: '$$$$',
        badge: 'Chef Approved',
        ctaText: 'Host The Ultimate Pizza Night',
        lifestyleImage: '/images/products/gozney-roccbox.png',
        description: 'Professional-grade insulation means this oven gets hot and stays hot. Rolling flame technology recreates traditional brick oven cooking in a portable package.',
        features: ['Portal Design', 'Safe-Touch Jacket', 'Built-in Thermometer', 'Retractable Legs'],
    },

    // Furniture - Dining Sets
    {
        id: 'polywood-lakeside-dining',
        name: 'Polywood Lakeside Dining Set',
        brand: 'Polywood',
        category: 'Furniture - Dining Sets',
        affiliateLink: 'https://amzn.to/3NtpRBU',
        priceTier: '$$$',
        badge: 'Buy It For Life',
        ctaText: 'Invest In Forever Furniture',
        lifestyleImage: '/images/products/polywood-lakeside-dining.png',
        description: 'Forget about sanding or staining. This HDPE lumber dining set handles rain, sun, and spills perfectly without rotting or fading.',
        features: ['HDPE Lumber', 'Weather-Proof', '20-Year Warranty', 'Made in USA'],
    },
    {
        id: 'walker-edison-delray',
        name: 'Walker Edison Delray Set',
        brand: 'Walker Edison',
        category: 'Furniture - Dining Sets',
        affiliateLink: 'https://amzn.to/49zbmoI',
        priceTier: '$$',
        badge: 'Best Seller',
        lifestyleImage: '/images/products/walker-edison-delray.png',
        description: 'Nothing beats the feel of real wood. This solid acacia dining set brings a natural, warm texture to your patio. Expandable table means you\'re ready for guests.',
        features: ['Solid Acacia Wood', 'Extendable Table', 'Chevron Design', 'Weather Treated'],
    },
    {
        id: 'grand-patio-bistro',
        name: 'Grand Patio Folding Bistro Set',
        brand: 'Grand Patio',
        category: 'Furniture - Dining Sets',
        affiliateLink: 'https://amzn.to/4jQR9hx',
        priceTier: '$$',
        badge: 'Small Space',
        ctaText: 'Transform Your Balcony',
        lifestyleImage: '/images/products/grand-patio-bistro.png',
        description: 'You don\'t need a huge yard to enjoy outdoor dining. This chic steel bistro set fits on the smallest balconies and folds flat when you need the space back.',
        features: ['Foldable', 'Powder Coated', 'Rust Resistant', 'No Assembly'],
    },

    // Furniture - Lounge & Seating
    {
        id: 'devoko-wicker-set',
        name: 'Devoko 3-Piece Wicker Set',
        brand: 'Devoko',
        category: 'Furniture - Lounge & Seating',
        affiliateLink: 'https://amzn.to/3Lq3EUR',
        priceTier: '$',
        badge: 'Budget Pick',
        ctaText: 'Create Your Nook',
        lifestyleImage: '/images/products/devoko-wicker-set.png',
        description: 'Create a cozy nook for under $100. Sturdy steel frames wrapped in PE wicker give you a stylish, weather-resistant spot to unwind.',
        features: ['PE Wicker', 'Sturdy Steel Frame', 'Easy Assembly', 'Washable Cushions'],
    },
    {
        id: 'keter-corfu-loveseat',
        name: 'Keter Corfu Loveseat',
        brand: 'Keter',
        category: 'Furniture - Lounge & Seating',
        affiliateLink: 'https://amzn.to/4t8pQ6X',
        priceTier: '$$',
        badge: 'Durable Resin',
        ctaText: 'Get Comfy',
        lifestyleImage: '/images/products/keter-corfu-loveseat.png',
        description: 'Durable resin construction with open-weave rattan look. Ergonomic, UV protected, and maintenance-free.',
        features: ['Resin Construction', 'UV Protected', 'Ergonomic Design', 'Weatherproof'],
    },
    {
        id: 'wisteria-lane-7-piece',
        name: 'Wisteria Lane 7-Piece Set',
        brand: 'Wisteria Lane',
        category: 'Furniture - Lounge & Seating',
        affiliateLink: 'https://amzn.to/3NwoORF',
        priceTier: '$$$',
        badge: 'Family Size',
        ctaText: 'Seat The Whole Family',
        lifestyleImage: '/images/products/wisteria-lane-7-piece.png',
        description: 'Dining/Conversation hybrid. Rattan with steel frame, plastic wood top table, and 3 footstools for extra seating.',
        features: ['7 Pieces', 'Sectional Sofa', 'Dining Table', 'Space Saving'],
    },
    {
        id: 'christopher-knight-egg-chair',
        name: 'Christopher Knight Egg Chair',
        brand: 'Christopher Knight',
        category: 'Furniture - Lounge & Seating',
        affiliateLink: 'https://amzn.to/45odayq',
        priceTier: '$$$$',
        badge: 'Statement Piece',
        ctaText: 'Float in Style',
        lifestyleImage: '/images/products/christopher-knight-egg-chair.png',
        description: 'Tear-drop hanging swing chair with stand. Black-brown faux wicker creates a cozy, floating retreat.',
        features: ['Hanging Design', 'Included Stand', 'Plush Cushions', 'Intricate Wicker'],
    },
    {
        id: 'generic-modular-sectional',
        name: '7-Piece Modular Sectional',
        brand: 'Generic',
        category: 'Furniture - Lounge & Seating',
        affiliateLink: 'https://amzn.to/4a5AweL',
        priceTier: '$$$',
        badge: 'Versatile',
        ctaText: 'Build Your Lounge',
        lifestyleImage: '/images/products/generic-modular-sectional.png',
        description: 'Rattan/Wicker modular sofa set with water-resistant cushions and coffee table. Reconfigure to fit your space.',
        features: ['Modular Design', 'Washable Covers', 'Tempered Glass', 'Clips Included'],
    },
    {
        id: 'best-choice-zero-gravity',
        name: 'Zero Gravity Chairs (Set of 2)',
        brand: 'Best Choice Products',
        category: 'Furniture - Lounge & Seating',
        affiliateLink: 'https://amzn.to/4qxS8WI',
        priceTier: '$$',
        badge: 'Comfort Pick',
        ctaText: 'Relax in Zero G',
        lifestyleImage: '/images/products/best-choice-zero-gravity.png',
        description: 'Adjustable steel mesh recliners with pillows and cup holder trays. Lockable reclining system glides smoothly.',
        features: ['Set of 2', 'Foldable', 'Cup Holders', 'UV-Resistant Mesh'],
    },

    // Shade Structures & Gazebos
    {
        id: 'purple-leaf-cantilever',
        name: 'Purple Leaf Cantilever Umbrella',
        brand: 'Purple Leaf',
        category: 'Shade Structures & Gazebos',
        affiliateLink: 'https://amzn.to/45RdF4a',
        priceTier: '$$',
        badge: 'Top Rated',
        ctaText: 'Stay Cool All Day',
        lifestyleImage: '/images/products/purple-leaf-cantilever.png',
        description: 'Chase the shade, not your chair. This heavy-duty offset umbrella rotates 360 degrees, covering your entire dining area without a center pole getting in the way.',
        features: ['360° Rotation', 'Double Top Canopy', 'All-Aluminum', 'Fade Resistant'],
    },
    {
        id: 'kozyard-alexander-gazebo',
        name: 'Kozyard Alexander Hardtop Gazebo',
        brand: 'Kozyard',
        category: 'Shade Structures & Gazebos',
        affiliateLink: 'https://amzn.to/4b5DDED',
        priceTier: '$$$$$',
        badge: 'Permanent',
        ctaText: 'Build Your Outdoor Room',
        lifestyleImage: '/images/products/kozyard-alexander-gazebo.png',
        description: '12\' x 16\' Aluminum Permanent Gazebo. Galvanized steel double roof handles heavy snow loads.',
        features: ['Rustproof Aluminum', 'Double Roof', 'Gutter System', 'Curtains & Netting'],
    },
    {
        id: 'purple-leaf-pergola',
        name: 'Purple Leaf Retractable Pergola',
        brand: 'Purple Leaf',
        category: 'Shade Structures & Gazebos',
        affiliateLink: 'https://amzn.to/3LKI2T8',
        priceTier: '$$$$$',
        badge: 'Modern Luxury',
        ctaText: 'Upgrade Your Shade',
        lifestyleImage: '/images/products/purple-leaf-pergola.png',
        description: '12\' x 14\' Aluminum Pergola with retractable rainproof roof and integrated LED string lights.',
        features: ['Retractable Roof', 'Aluminum Frame', 'Rainproof Fabric', 'Built-in LEDs'],
    },
    {
        id: 'yoleny-gazebo',
        name: 'YOLENY Hardtop Gazebo',
        brand: 'YOLENY',
        category: 'Shade Structures & Gazebos',
        affiliateLink: 'https://amzn.to/4bFrN4b',
        priceTier: '$$$$',
        badge: 'Solid Choice',
        ctaText: 'Get Covered',
        lifestyleImage: '/images/products/yoleny-gazebo.png',
        description: '12\' x 16\' Galvanized Steel Double Roof Gazebo. Includes curtains and netting for full enclosure.',
        features: ['Galvanized Steel', 'Double Top', 'Fully Enclosed', 'Heavy Duty'],
    },
    {
        id: 'veradek-privacy-screen',
        name: 'Veradek Privacy Screen',
        brand: 'Veradek',
        category: 'Shade Structures & Gazebos',
        affiliateLink: 'https://amzn.to/4pNCRQc',
        priceTier: '$$',
        badge: 'Instant Privacy',
        ctaText: 'Create Privacy',
        lifestyleImage: '/images/products/veradek-privacy-screen.png',
        description: 'Freestanding privacy divider. 76"H x 45"W. Durable weather-resistant plastic with a modern laser-cut pattern.',
        features: ['Freestanding', 'UV Resistant', 'Modern Pattern', 'Room Divider'],
    },

    // Lawn, Garden & Irrigation
    {
        id: 'segway-navimow',
        name: 'Segway Navimow i105N',
        brand: 'Segway',
        category: 'Lawn, Garden & Irrigation',
        affiliateLink: 'https://amzn.to/4r2gbN9',
        priceTier: '$$$',
        badge: 'Future Tech',
        ctaText: 'Automate Your Chores',
        lifestyleImage: '/images/products/segway-navimow.png',
        description: 'Throw away the perimeter wire. This AI-powered mower uses vision and satellite tech to mow your lawn perfectly while you relax.',
        features: ['Wire-Free', 'AI Mapping', 'VisionFence', 'App Control'],
    },
    {
        id: 'mammotion-luba',
        name: 'Mammotion LUBA mini AWD',
        brand: 'Mammotion',
        category: 'Lawn, Garden & Irrigation',
        affiliateLink: 'https://amzn.to/3NWfYg4',
        priceTier: '$$$$',
        badge: 'All Terrain',
        ctaText: 'Conquer The Hills',
        lifestyleImage: '/images/products/mammotion-luba.png',
        description: 'AWD Robot Mower for 0.37 Acre. Handles 80% slopes and rough terrain. Wire-free RTK setup.',
        features: ['All-Wheel Drive', 'Steep Slopes', 'Multi-Zone', 'No Perimeter Wire'],
    },
    {
        id: 'rachio-smart-sprinkler',
        name: 'Rachio Smart Sprinkler Controller',
        brand: 'Rachio',
        category: 'Lawn, Garden & Irrigation',
        affiliateLink: 'https://amzn.to/45RmxXw',
        priceTier: '$$',
        badge: 'Water Saver',
        ctaText: 'Save Water Now',
        lifestyleImage: '/images/products/rachio-smart-sprinkler.png',
        description: '16-Zone WiFi controller. Uses hyper-local weather intelligence to automatically skip watering during rain.',
        features: ['Weather Intelligence', 'App Control', 'Save Water', 'Easy Install'],
    },
    {
        id: 'orbit-b-hyve',
        name: 'Orbit B-hyve Smart Controller',
        brand: 'Orbit',
        category: 'Lawn, Garden & Irrigation',
        affiliateLink: 'https://amzn.to/4r4WAfs',
        priceTier: '$$',
        badge: 'Value Smart',
        ctaText: 'Get Smart',
        lifestyleImage: '/images/products/orbit-b-hyve.png',
        description: '12-Zone Indoor/Outdoor smart sprinkler controller. WaterSense certified for efficiency.',
        features: ['WaterSense', 'WiFi + Bluetooth', 'Weather Audits', 'Lockable Cabinet'],
    },

    // Lighting
    {
        id: 'brightech-solar-lights',
        name: 'Brightech Solar Lights',
        brand: 'Brightech',
        category: 'Lighting',
        affiliateLink: 'https://amzn.to/4b9c1yv',
        priceTier: '$$',
        badge: 'Solar Pick',
        ctaText: 'Light Up The Night',
        lifestyleImage: '/images/products/brightech_lights.png',
        description: 'No outlet? No problem. These commercial-grade solar strands charge all day and automatically bathe your patio in a warm, inviting glow at dusk.',
        features: ['Solar Powered', 'Shatterproof', 'Commercial Grade', 'Auto On/Off'],
    },
    {
        id: 'brightown-string-lights',
        name: 'Brightown String Lights',
        brand: 'Brightown',
        category: 'Lighting',
        affiliateLink: 'https://amzn.to/4qyKVpj',
        priceTier: '$',
        badge: 'Budget Glow',
        ctaText: 'Set The Mood',
        lifestyleImage: '/images/products/brightown_string_lights.png',
        description: '100FT of dimmable, waterproof perfection. Connect multiple strands to wrap your entire deck in festive light. IP65 rating means they stay up all year.',
        features: ['100FT Length', 'Dimmable', 'IP65 Waterproof', 'Shatterproof'],
    },

    // Outdoor Rugs & Décor
    {
        id: 'safavieh-courtyard-rug',
        name: 'Safavieh Courtyard Rug',
        brand: 'Safavieh',
        category: 'Outdoor Rugs & Décor',
        affiliateLink: 'https://amzn.to/4qsUiGR',
        priceTier: '$$',
        badge: 'Design Anchor',
        ctaText: 'Anchor Your Space',
        lifestyleImage: '/images/products/safavieh_rug.png',
        description: '10\'x14\' Washable outdoor rug in Natural & Cream. Instantly anchors your outdoor room.',
        features: ['Power Loomed', 'Weather Resistant', 'Easy Care', 'UV Stable'],
    },
    {
        id: 'gibson-melamine-dinnerware',
        name: 'Gibson Home Melamine Set',
        brand: 'Gibson Home',
        category: 'Outdoor Rugs & Décor',
        affiliateLink: 'https://amzn.to/4jTvPbx',
        priceTier: '$',
        badge: 'Dining Essential',
        ctaText: 'Dine Without Worry',
        lifestyleImage: '/images/products/gibson-melamine-dinnerware.png',
        description: 'Chip-resistant melamine dinnerware set. Looks like ceramic but durable enough for outdoor stone patios.',
        features: ['Melamine', 'Chip Resistant', 'Service for 4', 'Top Rack Safe'],
    },

    // Storage & Organization
    {
        id: 'keter-westwood-deck-box',
        name: 'Keter Westwood Deck Box',
        brand: 'Keter',
        category: 'Storage & Organization',
        affiliateLink: 'https://amzn.to/3YLMWSO',
        priceTier: '$$',
        badge: 'Storage King',
        ctaText: 'Declutter Your Patio',
        lifestyleImage: '/images/products/keter-westwood-deck-box.png',
        description: '150 Gallon Resin storage bench. Wood-plank look, lockable, and sturdy enough to seat 2 adults.',
        features: ['150 Gallon', 'Doubles as Bench', 'Fade Free', 'Lockable'],
    },

    // Lawn Games
    {
        id: 'gosports-giant-toppling-tower',
        name: 'GoSports Giant Toppling Tower',
        brand: 'GoSports',
        category: 'Lawn Games',
        affiliateLink: 'https://amzn.to/3NxAnbi',
        priceTier: '$$',
        badge: 'Party Game',
        ctaText: 'Start The Party',
        lifestyleImage: '/images/products/gosports-giant-toppling-tower.png',
        description: 'Starts at 2.5ft and grows to 5ft+. Includes 54 giant pine blocks and a robust carrying case.',
        features: ['Giant Size', 'Pine Wood', 'Carry Case', 'Dry Erase Rules'],
    },

    // Generators & Power
    {
        id: 'jackery-explorer-1000',
        name: 'Jackery Explorer 1000 v2',
        brand: 'Jackery',
        category: 'Generators & Power',
        affiliateLink: 'https://amzn.to/4b7sx1S',
        priceTier: '$$',
        badge: 'Portable Power',
        ctaText: 'Power Anywhere',
        lifestyleImage: '/images/products/jackery_explorer_1000.png',
        description: 'The standard for portable power. Lightweight, durable, and perfect for powering string lights, projectors, or charging laptops outside.',
        features: ['1002Wh Capacity', '1000W Output', 'Lightweight', '3 AC Outlets'],
    },
    {
        id: 'bluetti-ac200l',
        name: 'BLUETTI AC200L',
        brand: 'BLUETTI',
        category: 'Generators & Power',
        affiliateLink: 'https://amzn.to/3LWgKJy',
        priceTier: '$$$',
        badge: 'Heavy Duty',
        ctaText: 'Run Anything',
        lifestyleImage: '/images/products/bluetti_ac200l.png',
        description: 'A monster power station. 2400W output means it can run space heaters, electric grills, or power tools. Long-lasting LiFePO4 battery.',
        features: ['2400W Output', 'LiFePO4 Battery', 'Fast Charging', 'App Control'],
    },
    {
        id: 'jackery-solar-saga-100w',
        name: 'Jackery SolarSaga 100W Panel',
        brand: 'Jackery',
        category: 'Generators & Power',
        affiliateLink: 'https://amzn.to/4b7sx1S',
        priceTier: '$$',
        badge: 'Solar Essential',
        ctaText: 'Shop Solar Generator',
        lifestyleImage: '/images/products/jackery_solar_panel.png',
        description: 'Monocrystalline solar panels with high conversion efficiency. Foldable, portable, and designed to keep your power station topped up.',
        features: ['High Efficiency', 'Foldable', 'Kickstands', 'IP65 Water Resistant'],
    },
];

// Helper functions (Unchanged logic, just working with new data)
// Note: We changed category types to string to be more flexible since we now use specific category names
export function getProductsByCategory(category: string): Product[] {
    return sampleProducts.filter(p => p.category === category);
}

export function getProductById(id: string): Product | undefined {
    return sampleProducts.find(p => p.id === id);
}

export function getFeaturedProducts(count: number = 6): Product[] {
    return sampleProducts.filter(p => p.badge).slice(0, count);
}

export function getTopPick(category?: string): Product {
    if (category) {
        return sampleProducts.find(p => p.category === category && p.badge === 'Top Pick')
            || sampleProducts.filter(p => p.category === category)[0];
    }
    return sampleProducts.find(p => p.badge === 'Top Pick') || sampleProducts[0];
}
